---
- hosts: control
  become: true

  tasks:
    - name: install apps in this machine
      apt: 
        name: '{{item}}'
        state: present
        update_cache: yes
      with_items:
        - curl
        - elinks
      

