---
- hosts: database
  become: true
  #connection: ssh
  gather_facts: no
  tasks:
    - name: install mysql-server
      apt:
        name: mysql-server 
        state: present 
        update_cache: yes

    - name: ensure service started
      service: name=mysql state=started enabled=yes
